#Exhaustive Search

In [11]:
import urllib2  # the lib that handles the url stuff
import numpy as np
import pandas as pd

input_data = []
url = "http://www.cs.stir.ac.uk/~goc/source/easy20.txt"
data = urllib2.urlopen(url) # it's a file like object and works just like a file
for line in data: # files are iterable
    input_data.append(map(int,line.split()))

total_items = input_data.pop(0)[0] #total number of items in the item list
max_weight = input_data.pop()[0]  #max capacity
df = pd.DataFrame(input_data, columns=['no.', 'weight', 'value'])
df.head()

   no.  weight  value
0    1      91     29
1    2      60     65
2    3      61     71
3    4       9     60
4    5      79     45

In [2]:
#http://stackoverflow.com/questions/28111051/create-a-matrix-of-binary-represenation-of-numbers-in-python
#a function to generate a binary representaion of n in r bits 
#e.g. binrep(2,3) = '010'
def binrep(n,r):
    return "{0:0{1}b}".format(n, r)

In [4]:
#create matrix of all possible inputs
selected_items = []
for i in xrange(0, 2**total_items):
    s = binrep(i, total_items)
    selected_items.append(map(int, s))

In [7]:
#calculate all total weight
selected_items_array = np.array(selected_items)
weights = df.as_matrix(columns=["weight"])
values = df.as_matrix(columns=["value"])
total_weight = np.dot(selected_items_array, weights)
total_value = np.dot(selected_items_array, values)

In [15]:
selected_items = pd.DataFrame(selected_items_array)
selected_items["total_weight"] = total_weight
selected_items["total_value"] = total_value
print "maximum weight taken = ",max_weight
print "the total number of items = ",total_items
selected_items[selected_items["total_weight"] < max_weight].sort(["total_value"], ascending=0)[0:5]

maximum weight taken =  524
the total number of items =  20

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,total_weight,total_value
489164,0,1,1,1,0,1,1,1,0,1,...,1,1,0,0,1,1,0,0,517,787
491209,0,1,1,1,0,1,1,1,1,1,...,1,1,0,0,1,0,0,1,509,787
229066,0,0,1,1,0,1,1,1,1,1,...,1,1,0,0,1,0,1,0,522,785
229321,0,0,1,1,0,1,1,1,1,1,...,1,1,0,0,1,0,0,1,521,782
489161,0,1,1,1,0,1,1,1,0,1,...,1,1,0,0,1,0,0,1,501,781